// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
)

// MarshalJSON marshals as JSON.
func (s SHeader) MarshalJSON() ([]byte, error) {
	type SHeader struct {
	}
	var enc SHeader
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (s *SHeader) UnmarshalJSON(input []byte) error {
	type SHeader struct {
	}
	var dec SHeader
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	return nil
}
